title: Jennita Suttisaksunthron
logo: /portfolio/logo/logo.png
description: Bachalorâ€™s Degree student in 3rd year Computer Science Faculty of Science and Technology Thammasat University
#show_download: true
theme: jekyll-theme-minimal
