title: Jennita Suttisaksunthron
logo: /portfolio/assets/S__34717729.jpg
description: Bachalorâ€™s Degree student in 3rd year Computer Science Faculty of Science and Technology Thammasat University
#show_download: true
theme: jekyll-theme-minimal
